-- Data untuk laki-laki (man)
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('ACEH', 'man', 68.42);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SUMATERA UTARA', 'man', 68.06);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SUMATERA BARAT', 'man', 68.27);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('RIAU', 'man', 70.28);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('JAMBI', 'man', 69.83);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SUMATERA SELATAN', 'man', 68.74);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('BENGKULU', 'man', 67.99);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('LAMPUNG', 'man', 69.31);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KEP. BANGKA BELITUNG', 'man', 69.3);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KEP. RIAU', 'man', 68.99);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('DKI JAKARTA', 'man', 71.88);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('JAWA BARAT', 'man', 72.01);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('JAWA TENGAH', 'man', 72.95);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('DI YOGYAKARTA', 'man', 73.4);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('JAWA TIMUR', 'man', 70.16);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('BANTEN', 'man', 68.85);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('BALI', 'man', 70.99);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('NUSA TENGGARA BARAT', 'man', 65.54);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('NUSA TENGGARA TIMUR', 'man', 65.82);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KALIMANTAN BARAT', 'man', 69.38);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KALIMANTAN TENGAH', 'man', 68.36);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KALIMANTAN SELATAN', 'man', 67.49);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KALIMANTAN TIMUR', 'man', 72.96);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KALIMANTAN UTARA', 'man', 70.72);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SULAWESI UTARA', 'man', 70.44);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SULAWESI TENGAH', 'man', 67.24);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SULAWESI SELATAN', 'man', 69.28);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SULAWESI TENGGARA', 'man', 69.54);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('GORONTALO', 'man', 66.9);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SULAWESI BARAT', 'man', 64.11);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('MALUKU', 'man', 64.87);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('MALUKU UTARA', 'man', 67.17);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('PAPUA BARAT', 'man', 64.88);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('PAPUA', 'man', 64.53);

-- Data untuk perempuan (woman)
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('ACEH', 'woman', 72.35);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SUMATERA UTARA', 'woman', 72);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SUMATERA BARAT', 'woman', 72.21);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('RIAU', 'woman', 74.29);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('JAMBI', 'woman', 73.81);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SUMATERA SELATAN', 'woman', 72.68);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('BENGKULU', 'woman', 71.94);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('LAMPUNG', 'woman', 73.28);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KEP. BANGKA BELITUNG', 'woman', 73.26);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KEP. RIAU', 'woman', 72.94);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('DKI JAKARTA', 'woman', 75.61);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('JAWA BARAT', 'woman', 76.19);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('JAWA TENGAH', 'woman', 76.62);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('DI YOGYAKARTA', 'woman', 77.03);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('JAWA TIMUR', 'woman', 74.16);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('BANTEN', 'woman', 72.79);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('BALI', 'woman', 75.07);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('NUSA TENGGARA BARAT', 'woman', 69.5);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('NUSA TENGGARA TIMUR', 'woman', 69.8);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KALIMANTAN BARAT', 'woman', 73.35);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KALIMANTAN TENGAH', 'woman', 72.29);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KALIMANTAN SELATAN', 'woman', 71.45);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KALIMANTAN TIMUR', 'woman', 76.62);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('KALIMANTAN UTARA', 'woman', 74.75);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SULAWESI UTARA', 'woman', 74.46);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SULAWESI TENGAH', 'woman', 71.2);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SULAWESI SELATAN', 'woman', 73.24);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SULAWESI TENGGARA', 'woman', 73.51);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('GORONTALO', 'woman', 70.87);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('SULAWESI BARAT', 'woman', 68);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('MALUKU', 'woman', 68.8);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('MALUKU UTARA', 'woman', 71.14);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('PAPUA BARAT', 'woman', 68.81);
INSERT INTO "ahh" ("province", "gender", "age") VALUES ('PAPUA', 'woman', 68.45);
